### ISSUE TITLE
When a non registered/not logged in user creates a todo list, delete the todo list after they leave the website

### ISSUE THREAD

**Issue by KarloParagas** [EthanMartino/ToDoList#43]
Since every todo lists created gets added to the database, it'd be nice to find out a way to delete the todo list automatically from the database once the non registered/not logged in user exits out of the website. That way, the database doesn't get overloaded with "temporary/one time" todo lists.

**Comment by EthanMartino** [comment]
One way of completing this is through Azure Functions:
https://markheath.net/post/ef-core-di-azure-functions
